# Generated by Django 3.2.3 on 2021-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='camera',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
