# Generated by Django 3.2.3 on 2021-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0002_absensi_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='camera',
            field=models.IntegerField(default=1),
        ),
    ]
