# Generated by Django 3.2.3 on 2021-06-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0003_alter_absensi_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='camera',
        ),
    ]
