# Generated by Django 3.2.3 on 2021-06-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0004_remove_absensi_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nip',
            field=models.IntegerField(max_length=255, unique=True),
        ),
    ]
