# Generated by Django 3.2.3 on 2021-06-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0005_alter_employee_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nip',
            field=models.IntegerField(unique=True),
        ),
    ]
