# Generated by Django 3.2.3 on 2021-07-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0010_auto_20210708_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='kamera',
        ),
        migrations.DeleteModel(
            name='Kamera',
        ),
    ]
