# Generated by Django 3.2.3 on 2021-07-12 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0022_absensi_kamera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 23, 12, 44, 211013)),
        ),
        migrations.AlterField(
            model_name='kamera',
            name='periode_absensi',
            field=models.TextField(),
        ),
    ]
