# Generated by Django 3.2.3 on 2021-07-17 23:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misweb', '0023_auto_20210712_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='first_seen',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 23, 20, 31, 341598)),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
